# Copyright 2020 DigitalOcean
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: License
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: download addlicense
        run: go get -d github.com/google/addlicense
      - name: install addlicense
        run: go build -o addlicense github.com/google/addlicense
      - name: run license addition
        run: ./addlicense -c DigitalOcean -l apache -y 2021 --check .
